# Generated by Django 4.2 on 2023-08-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscribes_author_subscribes_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_private',
            new_name='is_private',
        ),
        migrations.AddField(
            model_name='user',
            name='is_receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Подписан на рассылку?'),
        ),
    ]
