# Generated by Django 4.2 on 2023-08-07 15:03

from django.db import migrations, models
import django.db.models.deletion
import main.mixins
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Доступ к карточке',
                'verbose_name_plural': 'Доступ к карточкам',
            },
        ),
        migrations.CreateModel(
            name='CardLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='card_image')),
                ('is_private', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
            bases=(main.mixins.CompressImageOnSaveMixin, main.mixins.ResizeImageOnSaveMixin, main.models.CountableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CardViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_created', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Доступ к теме',
                'verbose_name_plural': 'Доступ к темам',
            },
        ),
        migrations.CreateModel(
            name='ThemeLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='themes_image')),
                ('is_private', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
            bases=(main.mixins.CompressImageOnSaveMixin, main.mixins.ResizeImageOnSaveMixin, main.models.CountableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CardComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.comments')),
            ],
            bases=('main.comments',),
        ),
        migrations.CreateModel(
            name='ThemeComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.comments')),
            ],
            bases=('main.comments',),
        ),
        migrations.CreateModel(
            name='ThemeViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.themes')),
            ],
        ),
    ]
