# Generated by Django 4.2 on 2023-08-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='themeviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themes',
            name='sub_theme_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.themes', verbose_name='Подтема для'),
        ),
        migrations.AddField(
            model_name='themes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='themelikes',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.themes'),
        ),
        migrations.AddField(
            model_name='themelikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themeaccess',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.themes'),
        ),
        migrations.AddField(
            model_name='themeaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='sub_comment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardviews',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cards'),
        ),
        migrations.AddField(
            model_name='cardviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cards',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.themes', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='cards',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='cardlikes',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cards'),
        ),
        migrations.AddField(
            model_name='cardlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardaccess',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cards'),
        ),
        migrations.AddField(
            model_name='cardaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themecomments',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.themes'),
        ),
        migrations.AddField(
            model_name='cardcomments',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cards'),
        ),
    ]
