# Generated by Django 4.2 on 2023-06-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_themes_sub_theme_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='sub_theme_to',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
