# Generated by Django 4.2 on 2023-08-15 13:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def compute_search_vector(apps, ):
    model = apps.get_model("Themes")
    model.objects.update(search_vector=django.contrib.postgres.search.SearchVector("title"))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='themes',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_themes_search__ec7590_gin'),
        ),
    ]
