# Generated by Django 4.2 on 2023-07-20 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcomments',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cardcomments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cardcomments',
            name='sub_comment_to',
        ),
        migrations.RemoveField(
            model_name='cardcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='themecomments',
            name='content',
        ),
        migrations.RemoveField(
            model_name='themecomments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='themecomments',
            name='sub_comment_to',
        ),
        migrations.RemoveField(
            model_name='themecomments',
            name='user',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_created', models.TimeField(auto_now_add=True)),
                ('sub_comment_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cardcomments',
            name='comments_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True, serialize=False, to='main.comments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themecomments',
            name='comments_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.comments'),
            preserve_default=False,
        ),
    ]
