# Generated by Django 4.2 on 2023-08-15 13:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def compute_search_vector(apps):
    model = apps.get_model("Cards")
    model.objects.update(search_vector=django.contrib.postgres.search.SearchVector("title", "content"))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_themes_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='cards',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_cards_search__b32a70_gin'),
        ),
    ]
