# Generated by Django 4.2 on 2023-07-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cardcomments_content_remove_cardcomments_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardlikes',
            old_name='card',
            new_name='obj',
        ),
        migrations.RenameField(
            model_name='themelikes',
            old_name='theme',
            new_name='obj',
        ),
    ]
