# Generated by Django 4.2 on 2023-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='image',
            field=models.ImageField(blank=True, upload_to='card_image'),
        ),
        migrations.AddField(
            model_name='cards',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='themes',
            name='image',
            field=models.ImageField(blank=True, upload_to='themes_image'),
        ),
        migrations.AddField(
            model_name='themes',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
