# Generated by Django 4.2 on 2023-08-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cards_search_vector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themeaccess',
            old_name='parent_theme',
            new_name='theme',
        ),
    ]
