# Generated by Django 4.2 on 2023-07-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cards_image_cards_is_private_themes_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.themes', verbose_name='Тема'),
        ),
    ]
