# Generated by Django 4.2 on 2023-08-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_parent_theme_themeaccess_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcomments',
            old_name='obj',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardlikes',
            old_name='obj',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardviews',
            old_name='obj',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='themecomments',
            old_name='obj',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='themelikes',
            old_name='obj',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='themeviews',
            old_name='obj',
            new_name='theme',
        ),
    ]
