# Generated by Django 4.2 on 2023-08-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_card_cardcomments_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcomments',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cards'),
        ),
        migrations.AlterField(
            model_name='themecomments',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.themes'),
        ),
    ]
